paramWinModels.reportparameter = {
  id:"38c43a06-a567-4b84-a4e2-dd255232de09",
  name:"reportparameter",
  units:{
    companycode:{
      id:"d2c36d8c-06ab-4522-a447-72d25b09943c",
      name:"companycode",
      label:"单位编号",
      valueType:valueType.string,
      inputHelpType:"",
      inputHelpName:"",
      decimalNum:"0",
      valueLength:100,
      isMultiValue:false,
      isNullable:true,
      isEditable:true,
      unitType:"text",
      defaultValue:"",
    },
    month:{
      id:"8aa4d746-b45b-4f03-8871-b096f0449ad6",
      name:"month",
      label:"月份",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"sys_date_month",
      decimalNum:"0",
      valueLength:100,
      isMultiValue:false,
      isNullable:false,
      isEditable:true,
      unitType:"list",
      maps:{"month":"month"},
      list:{
        name:"sys_date_month",
        columns:[{field:"month",valueType:valueType.string,title:"月份",width:100,hidden:false}
        ]
      },
      defaultValue:"",
    },
    year:{
      id:"273e3204-2333-451a-a0f4-addae7bcc9f9",
      name:"year",
      label:"年份",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"sys_date_year",
      decimalNum:"0",
      valueLength:100,
      isMultiValue:false,
      isNullable:false,
      isEditable:true,
      unitType:"list",
      maps:{"year":"year"},
      list:{
        name:"sys_date_year",
        columns:[{field:"year",valueType:valueType.string,title:"年份",width:100,hidden:false}
        ]
      },
      defaultValue:"",
    },
    company:{
      id:"6324bb6e-0618-4816-b28b-19dab7005573",
      name:"company",
      label:"单位",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"report_company",
      decimalNum:"0",
      valueLength:100,
      isMultiValue:false,
      isNullable:true,
      isEditable:true,
      unitType:"list",
      maps:{"company":"name","companycode":"code"},
      list:{
        name:"report_company",
        columns:[{field:"id",valueType:valueType.string,title:"主键",width:0,hidden:true},
{field:"name",valueType:valueType.string,title:"名称",width:100,hidden:false},
{field:"code",valueType:valueType.string,title:"编号",width:0,hidden:true},
{field:"partcode",valueType:valueType.string,title:"级数",width:0,hidden:true}
        ]
      },
      defaultValue:"",
    }
  }
}
