var supportiveSearchTypes = {
	all: {code: "all", name: "全部"},
	zgls_ChaoDai: {code: "zgls_ChaoDai", category:"zgls", name: "中国历史-朝代", color: "#336699"},
	zgls_ShiQi: {code: "zgls_ShiQi", category:"zgls", name: "中国历史-时期", color: "#CC9900"},
	zgls_ShiJian: {code: "zgls_ShiJian", category:"zgls", name: "中国历史-事件", color: "#009999"},
	zgls_NianFen: {code: "zgls_NianFen", category:"zgls", name: "中国历史-年份", color: "#666699"},
	zgls_DiWang: {code: "zgls_DiWang", category:"zgls", name: "中国历史-帝王", color: "#CC6600"},
	zgls_RenWu: {code: "zgls_RenWu", category:"zgls", name: "中国历史-人物", color: "#CCCC00"},
	zgls_ChaoDai_ChaoDai: {code: "zgls_ChaoDai_ChaoDai", category:"zgls", name: "关系：中国历史朝代更迭", color: "#006633"},
	zgls_ChaoDai_ShiQi: {code: "zgls_ChaoDai_ShiQi", category:"zgls", name: "关系：中国朝代与时期", color: "#993366"},
	zgls_DiWang_ChaoDai: {code: "zgls_DiWang_ChaoDai", category:"zgls", name: "关系：中国帝王与朝代", color: "#666633"},
	zgls_ShiJian_ChaoDai: {code: "zgls_ShiJian_ChaoDai", vname: "关系：中国历史事件与朝代", color: "#666633"}, 
	zgls_ShiJian_ShiQi: {code: "zgls_ShiJian_ShiQi", category:"zgls", name: "关系：中国历史事件与时期", color: "#666633"},
	bk_Book: {code: "bk_Book", category:"bk", name: "书籍", color: "#336699"},
	bk_Book: {code: "bk_BookPage", category:"bk", name: "书籍页面", color: "#666699"},
	bj_KGraph: {code: "bj_KGraph", category:"gx", name: "图谱", color: "#CC6600"},
	gx_ChengYu: {code: "gx_ChengYu", category:"gx", name: "成语", color: "#009999"},
	gx_DianGu: {code: "gx_DianGu", category:"gx", name: "典故", color: "#CC6600"},
	gx_DiMing: {code: "gx_DiMing", category:"gx", name: "地名", color: "#336699"},
	gx_GuanZhi: {code: "gx_GuanZhi", category:"gx", name: "官职", color: "#CC6600"},
	gx_HanZi: {code: "gx_HanZi", category:"gx", name: "汉字", color: "#CC9900"},
	gx_RenWu: {code: "gx_RenWu", category:"gx", name: "人物", color: "#009999"},
	gx_ShiCi: {code: "gx_ShiCi", category:"gx", name: "诗词", color: "#666699"},
	gx_ShiJian: {code: "gx_ShiJian", category:"gx", name: "事件", color: "#CC6600"},
	gx_WenXueZuoPin: {code: "gx_WenXueZuoPin", category:"gx", name: "文学作品", color: "#CCCC00"},
	gx_WenXueZuoPin_Juan: {code: "gx_WenXueZuoPin_Juan", category:"gx", name: "书目", color: "#CC6600"},
	gx_WenXueZuoPin2Juan: {code: "gx_WenXueZuoPin2Juan", category:"gx", name: "关系：卷-文学作品", color: "#666633"},
	dlxz_XZQH: {code:"dlxz_XZQH", category:"dlxz", name: "中国行政区划", color: "#666699"},
	dlxz_TJYQHDM: {code:"dlxz_TJYQHDM", category:"dlxz", name: "统计用区划代码", color: "#666699"},
	dlxz_DQJJ: {code:"dlxz_DQJJ", category:"dlxz", name: "中国地区简介", color: "#666699"},
	dlxz_GJDQ: {code:"dlxz_GJDQ", category:"dlxz", name: "全球国家地区", color: "#666699"},
	dlxz_MGZXX: {code:"dlxz_MGZXX", category:"dlxz", name: "美国各州信息", color: "#666699"},
	dlxz_POI_MenZhen: {code:"dlxz_POI_MenZhen", category:"dlxz", name: "POI门诊", color: "#666699"},
	dlxz_POI_GouWu: {code:"dlxz_POI_GouWu", category:"dlxz", name: "POI购物", color: "#666699"},
	dlxz_POI_QiCheWeiXiu: {code:"dlxz_POI_QiCheWeiXiu", category:"dlxz", name: "POI汽车维修", color: "#666699"},
	dlxz_POI_XieZiLou: {code:"dlxz_POI_XieZiLou", category:"dlxz", name: "POI写字楼", color: "#666699"},
	dlxz_POI_XueXiao: {code:"dlxz_POI_XueXiao", category:"dlxz", name: "POI学校", color: "#666699"},
	dlxz_POI_YiYuan: {code:"dlxz_POI_YiYuan", category:"dlxz", name: "POI医院", color: "#666699"},
	dlxz_POI_ZhengFuJiGuan: {code:"dlxz_POI_ZhengFuJiGuan", category:"dlxz", name: "POI政府机关", color: "#666699"},
	dlxz_SSDT: {code:"dlxz_SSDT", category:"dlxz", name: "省市地图", color: "#666699"},
	dlxz_ShengXQDT: {code:"dlxz_ShengXQDT", category:"dlxz", name: "省县区地图", color: "#666699"},
	ssgs_GGGRXX: {code:"ssgs_GGGRXX", category:"ssgs", name: "上市公司高管个人信息", color: "#666699"},
	ssgs_GGZWXX: {code:"ssgs_GGZWXX", category:"ssgs", name: "上市公司高管职务信息", color: "#666699"},
	ssgs_HSGS: {code:"ssgs_HSGS", category:"ssgs", name: "沪深股市上市公司", color: "#666699"},
	ssgs_Report: {code:"ssgs_Report", category:"ssgs", name: "上市公司季、半年、年报", color: "#666699"},
	ssgs_CWBGSJYJXXBN: {code:"ssgs_CWBGSJYJXXBN", category:"ssgs", name: "财务报告审计意见信息表（年）", color: "#666699"},
	ssgs_SSGSCWZBSJBN: {code:"ssgs_SSGSCWZBSJBN", category:"ssgs", name: "上市公司财务指标数据表（年）", color: "#666699"},
	ssgs_SSGSCWWGBR: {code:"ssgs_SSGSCWWGBR", category:"ssgs", name: "上市公司财务违规表（日）", color: "#666699"},
	ssgs_SSGSCWCSZKBR: {code:"ssgs_SSGSCWCSZKBR", category:"ssgs", name: "上市公司财务重述情况表（日）", color: "#666699"},
	ssgs_KJWJXZBBACFMON: {code:"ssgs_KJWJXZBBACFMON", category:"ssgs", name: "会计稳健性指标表-ACF模型（年）", color: "#666699"},
	ssgs_KJWJXZBBBASUMXN: {code:"ssgs_KJWJXZBBBASUMXN", category:"ssgs", name: "会计稳健性指标表-Basu模型（年）", color: "#666699"},
	ssgs_KJWJXZBBCSCOREMXN: {code:"ssgs_KJWJXZBBCSCOREMXN", category:"ssgs", name: "会计稳健性指标表-CScore模型（年）", color: "#666699"},
	ssgs_KJXXKBXZBBN: {code:"ssgs_KJXXKBXZBBN", category:"ssgs", name: "会计信息可比性指标表（年）", color: "#666699"},
	ssgs_KJXXKBXZBBGSJDBN: {code:"ssgs_KJXXKBXZBBGSJDBN", category:"ssgs", name: "会计信息可比性指标表-公司间对比（年）", color: "#666699"},
	ssgs_KJXXPLJSXZBBN: {code:"ssgs_KJXXPLJSXZBBN", category:"ssgs", name: "会计信息披露及时性指标表（年）", color: "#666699"},
	ssgs_SSGSXXPLKPXXBN: {code:"ssgs_SSGSXXPLKPXXBN", category:"ssgs", name: "上市公司信息披露考评信息表（年）", color: "#666699"},
	ssgs_YYFYXSZBBN: {code:"ssgs_YYFYXSZBBN", category:"ssgs", name: "盈余反应系数指标表（年）", color: "#666699"},
	ssgs_YJYYGLZBBDDMXN: {code:"ssgs_YJYYGLZBBDDMXN", category:"ssgs", name: "应计盈余管理指标表-DD模型（年）", color: "#666699"},
	ssgs_YJYYGLZBBFXXYJMXN: {code:"ssgs_YJYYGLZBBFXXYJMXN", category:"ssgs", name: "应计盈余管理指标表-非线性应计模型（年）", color: "#666699"},
	ssgs_YJYYGLZBBXZJONESMXN: {code:"ssgs_YJYYGLZBBXZJONESMXN", category:"ssgs", name: "应计盈余管理指标表-修正Jones模型（年）", color: "#666699"},
	ssgs_ZSYYGLZBBN: {code:"ssgs_ZSYYGLZBBN", category:"ssgs", name: "真实盈余管理指标表（年）", color: "#666699"},
	ssgs_YYPLZLZBBN: {code:"ssgs_YYPLZLZBBN", category:"ssgs", name: "盈余披露质量指标表（年）", color: "#666699"}
};
var supportiveNGraphKeyColors = {
	currentNodeColor: "#DC143C",
	currentRelationColor: "#DC143C"	
};