viewModels.con_projectunit_model = {
  id:"2e56c84c-189f-47aa-8787-e0f143521f97",
  name:"con_projectunit_model",
  dataName:"con_projectunit_model",
  title:"单体管理模型",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:30, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, align:'center', edittype:"checkbox", dispunitType:"checkbox"},
    {name:"id", label:"id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"project", label:"项目", width:260, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"pop"},
    {name:"projectid", label:"项目id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"projectunit", label:"单体工程", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"pop"},
    {name:"projectunitid", label:"单体工程id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"code", label:"模型编码", width:150, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"pop"},
    {name:"name", label:"模型名称", width:200, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"versionnum", label:"版本号", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"companyid", label:"企业id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"componentid", label:"组装模型id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"categoryid", label:"类型id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"categoryname", label:"类型", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"categorycode", label:"分类编码", width:100, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createtime", label:"创建时间", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"createusername", label:"创建人", width:0, hidden:true, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"createuser_xid", label:"创建人id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"deletetime", label:"删除时间", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"modifyuser_xid", label:"修改人id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"modifyusername", label:"修改人", width:0, hidden:true, sortable:true, search:true, resizable:true, editable:true, align:'', canEdit:true, nullable:true, edittype:"", dispunitType:""},
    {name:"modifytime", label:"修改时间", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"ncpRowOperate", label:"操作", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:false, canEdit:false, nullable:true, align:'center'}
  ],
  dispUnitModel:[
    {name:"id", label:"id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"project", label:"项目", editable:true,nullable:false, hidden:false, dispunitType:"pop", },
    {name:"projectid", label:"项目id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"projectunit", label:"单体工程", editable:true,nullable:false, hidden:false, dispunitType:"pop", },
    {name:"projectunitid", label:"单体工程id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"code", label:"模型编码", editable:true,nullable:false, hidden:false, dispunitType:"pop", },
    {name:"name", label:"模型名称", editable:false,nullable:true, hidden:false, dispunitType:"text", },
    {name:"versionnum", label:"版本号", editable:false,nullable:true, hidden:false, dispunitType:"text", },
    {name:"companyid", label:"企业id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"componentid", label:"组装模型id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"categoryid", label:"类型id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"categoryname", label:"类型", editable:false,nullable:true, hidden:false, dispunitType:"text", },
    {name:"categorycode", label:"分类编码", editable:false,nullable:true, hidden:true, dispunitType:"text", },
    {name:"createtime", label:"创建时间", editable:true,nullable:true, hidden:true, dispunitType:"time", },
    {name:"createusername", label:"创建人", editable:true,nullable:true, hidden:true, dispunitType:"pop", },
    {name:"createuser_xid", label:"创建人id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"deletetime", label:"删除时间", editable:true,nullable:true, hidden:true, dispunitType:"time", },
    {name:"modifyuser_xid", label:"修改人id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"modifyusername", label:"修改人", editable:true,nullable:true, hidden:true, dispunitType:"", },
    {name:"modifytime", label:"修改时间", editable:true,nullable:true, hidden:true, dispunitType:"time", }
  ]
}
