viewModels.mdl_Component = {
  id:"32f4f833-5c51-40e0-95fd-76ae3539c0db",
  name:"mdl_Component",
  dataName:"mdl_Component",
  title:"组件",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:30, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, align:'center', edittype:"checkbox", dispunitType:"checkbox"},
    {name:"id", label:"id", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"code", label:"编码", width:180, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"name", label:"名称", width:180, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"versionnum", label:"版本号", width:50, hidden:false, sortable:true, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"categoryid", label:"类型ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"categorycode", label:"类型编码", width:120, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"categoryname", label:"类型名称", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"ispublished", label:"已发布", width:50, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'center', canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"createtime", label:"创建时间", width:100, hidden:false, sortable:true, search:false, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"modifytime", label:"修改时间", width:100, hidden:false, sortable:true, search:false, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"createuser", label:"创建人", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"note", label:"备注", width:200, hidden:false, sortable:false, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"sharetype", label:"共享范围", width:80, hidden:false, sortable:false, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"list"},
    {name:"gbcode", label:"国标码", width:180, hidden:false, sortable:false, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"goods_mid", label:"商品流水码", width:100, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"metadata", label:"基础属性", width:100, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_904", label:"辅计量单位", width:80, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"s_base_mid", label:"基础属性编码", width:20, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"project", label:"项目", width:160, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"projectid", label:"项目id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"projectunit", label:"项目单体", width:100, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"projectunitid", label:"项目单体id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_900", label:"物料名称", width:50, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"ncpRowOperate", label:"操作", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:false, canEdit:false, nullable:true, align:'center'}
  ],
  dispUnitModel:[
    {name:"id", label:"id", editable:false,nullable:true, hidden:true, dispunitType:"text", },
    {name:"code", label:"编码", editable:false,nullable:true, hidden:false, dispunitType:"text", },
    {name:"name", label:"名称", editable:false,nullable:true, hidden:false, dispunitType:"text", },
    {name:"versionnum", label:"版本号", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"categoryid", label:"类型ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"categorycode", label:"类型编码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"categoryname", label:"类型名称", editable:true,nullable:true, hidden:false, dispunitType:"pop", },
    {name:"ispublished", label:"已发布", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", },
    {name:"createtime", label:"创建时间", editable:false,nullable:true, hidden:false, dispunitType:"time", },
    {name:"modifytime", label:"修改时间", editable:false,nullable:true, hidden:false, dispunitType:"time", },
    {name:"createuser", label:"创建人", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"note", label:"备注", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"sharetype", label:"共享范围", editable:true,nullable:false, hidden:false, dispunitType:"list", },
    {name:"gbcode", label:"国标码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"goods_mid", label:"商品流水码", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"metadata", label:"基础属性", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"m_904", label:"辅计量单位", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"s_base_mid", label:"基础属性编码", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"project", label:"项目", editable:true,nullable:true, hidden:true, dispunitType:"pop", },
    {name:"projectid", label:"项目id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"projectunit", label:"项目单体", editable:true,nullable:true, hidden:true, dispunitType:"pop", },
    {name:"projectunitid", label:"项目单体id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"m_900", label:"物料名称", editable:true,nullable:true, hidden:true, dispunitType:"text", }
  ]
}
