viewModels.mdl_extendmaterial = {
  id:"a34876e8-a0ab-4aa0-be81-1b985c4d834d",
  name:"mdl_extendmaterial",
  dataName:"mdl_extendmaterial",
  title:"业务系统根据自身需求获取基础信息",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:30, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, align:'center', edittype:"checkbox", dispunitType:"checkbox"},
    {name:"m_900", label:"物料名称", width:120, hidden:false, sortable:false, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_904", label:"辅计量单位", width:80, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"s_base_mid", label:"基础属性编码", width:160, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"goods_mid", label:"商品流水码", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"s_goods_mid", label:"扩展码-国标", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"base_mid", label:"基础属性编码-流水码", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"s_mid", label:"物料编码-国标码", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"mid", label:"物料编码-流水码", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_200", label:"花色", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_201", label:"样式", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_202", label:"形状", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_203", label:"质感", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_204", label:"品牌", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_261", label:"系列", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_262", label:"配件", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_263", label:"型号", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_264", label:"功能", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_265", label:"支撑件", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_266", label:"用途", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_267", label:"模具型号", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_300", label:"材质", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_301", label:"(面板)材质", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_302", label:"密度", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_303", label:"容重", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_304", label:"克重", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_305", label:"压强(kpa)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_306", label:"防火等级", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_307", label:"阻燃等级", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_308", label:"环保等级", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_309", label:"防水等级", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_310", label:"防盗等级", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_311", label:"能效等级", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_312", label:"排风量", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_313", label:"功率", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_314", label:"支撑力度", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_315", label:"负荷压力", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_316", label:"电压(V)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_317", label:"电流(A)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_318", label:"色温", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_319", label:"质量等级", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_400", label:"规格", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_401", label:"长度(mm)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_402", label:"宽度(mm)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_403", label:"高度(mm)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_404", label:"厚度(mm)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_405", label:"壁厚(mm)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_406", label:"直径(mm)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_407", label:"重量", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_408", label:"容量", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_409", label:"冲水量", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_410", label:"开孔尺寸", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_411", label:"坑距(mm)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_412", label:"屏幕尺寸", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_413", label:"外侧门框高度(mm)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_414", label:"内侧门框高度(mm)", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"m_415", label:"最小包装规格", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_500", label:"构造", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_501", label:"表层工艺", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_502", label:"加工工艺", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_503", label:"拉手类型", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_504", label:"门窗套边", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_505", label:"锁体类型", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_506", label:"地漏样式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_507", label:"玻璃类型", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_508", label:"安装方式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_509", label:"控制方式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_510", label:"排水方式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_511", label:"排烟方式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_512", label:"光源类型", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_513", label:"开槽方式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_514", label:"轨道类型", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_515", label:"窗耳类型", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_516", label:"开启方向", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_903", label:"标准单位", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_905", label:"物料所属分类", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_906", label:"制备名称", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_907", label:"物料别名", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_908", label:"U8编码", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_909", label:"U8名称", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_911", label:"换算率", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_913", label:"适用空间", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"_1sttypecode", label:"物料一级分类编码", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"_1sttypename", label:"物料一级分类名称", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"_2ndtypecode", label:"物料二级分类编码", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"_2ndtypename", label:"物料二级分类名称", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"_3thtypename", label:"物料三级分类名称", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"enablestate", label:"是否停用", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"modifyid", label:"是否变更", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"m_517", label:"电盒点位", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_518", label:"墙体类型", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"m_519", label:"是否使用内凹式踢脚线", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"ncpRowOperate", label:"操作", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:false, canEdit:false, nullable:true, align:'center'}
  ],
  dispUnitModel:[
    {name:"m_900", label:"物料名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_904", label:"辅计量单位", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"s_base_mid", label:"基础属性编码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"goods_mid", label:"商品流水码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"s_goods_mid", label:"扩展码-国标", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"base_mid", label:"基础属性编码-流水码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"s_mid", label:"物料编码-国标码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"mid", label:"物料编码-流水码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_200", label:"花色", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_201", label:"样式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_202", label:"形状", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_203", label:"质感", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_204", label:"品牌", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_261", label:"系列", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_262", label:"配件", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_263", label:"型号", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_264", label:"功能", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_265", label:"支撑件", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_266", label:"用途", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_267", label:"模具型号", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_300", label:"材质", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_301", label:"(面板)材质", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_302", label:"密度", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_303", label:"容重", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_304", label:"克重", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_305", label:"压强(kpa)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_306", label:"防火等级", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_307", label:"阻燃等级", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_308", label:"环保等级", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_309", label:"防水等级", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_310", label:"防盗等级", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_311", label:"能效等级", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_312", label:"排风量", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_313", label:"功率", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_314", label:"支撑力度", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_315", label:"负荷压力", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_316", label:"电压(V)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_317", label:"电流(A)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_318", label:"色温", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_319", label:"质量等级", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_400", label:"规格", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_401", label:"长度(mm)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_402", label:"宽度(mm)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_403", label:"高度(mm)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_404", label:"厚度(mm)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_405", label:"壁厚(mm)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_406", label:"直径(mm)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_407", label:"重量", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_408", label:"容量", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_409", label:"冲水量", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_410", label:"开孔尺寸", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_411", label:"坑距(mm)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_412", label:"屏幕尺寸", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_413", label:"外侧门框高度(mm)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_414", label:"内侧门框高度(mm)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"m_415", label:"最小包装规格", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_500", label:"构造", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_501", label:"表层工艺", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_502", label:"加工工艺", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_503", label:"拉手类型", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_504", label:"门窗套边", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_505", label:"锁体类型", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_506", label:"地漏样式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_507", label:"玻璃类型", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_508", label:"安装方式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_509", label:"控制方式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_510", label:"排水方式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_511", label:"排烟方式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_512", label:"光源类型", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_513", label:"开槽方式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_514", label:"轨道类型", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_515", label:"窗耳类型", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_516", label:"开启方向", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_903", label:"标准单位", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_905", label:"物料所属分类", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_906", label:"制备名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_907", label:"物料别名", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_908", label:"U8编码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_909", label:"U8名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_911", label:"换算率", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_913", label:"适用空间", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"_1sttypecode", label:"物料一级分类编码", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"_1sttypename", label:"物料一级分类名称", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"_2ndtypecode", label:"物料二级分类编码", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"_2ndtypename", label:"物料二级分类名称", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"_3thtypename", label:"物料三级分类名称", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"enablestate", label:"是否停用", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"modifyid", label:"是否变更", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"m_517", label:"电盒点位", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_518", label:"墙体类型", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"m_519", label:"是否使用内凹式踢脚线", editable:true,nullable:true, hidden:false, dispunitType:"text", }
  ]
}
