viewModels.mtl_Material = {
  id:"6a40c7e5-1874-4041-be8d-15a065376e0c",
  name:"mtl_Material",
  dataName:"mtl_Material",
  title:"材质表",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:30, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, align:'center', edittype:"checkbox", dispunitType:"checkbox"},
    {name:"id", label:"id", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"code", label:"编码", width:150, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"name", label:"名称", width:150, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"isactive", label:"已启用", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'center', canEdit:true, nullable:false, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"ispublic", label:"是否公共", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'center', canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"typename", label:"基础材质", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"typeid", label:"基础材质ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"typecode", label:"类型编码", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"color", label:"颜色", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"imageaccessoryid", label:"贴图附件ID", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, align:'left', canEdit:false, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"imagename", label:"贴图", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"normalimageaccessoryid", label:"法线贴图ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"normalimagename", label:"法线贴图", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"opacity", label:"透明度", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"opacityimageaccessoryid", label:"透明度贴图ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"opacityimagename", label:"透明度贴图", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"metalness", label:"金属度", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"metalnessimageaccessoryid", label:"金属度贴图ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"metalnessimagename", label:"金属度贴图", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"roughness", label:"粗糙度", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"roughnessimageaccessoryid", label:"粗糙度贴图ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"roughnessimagename", label:"粗糙度贴图", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"scalewidth", label:"宽度比例", width:70, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"scaleheight", label:"高度比例", width:70, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"description", label:"描述", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createuser_xid", label:"创建人id", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createusername", label:"创建人", width:80, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"createtime", label:"创建时间", width:150, hidden:false, sortable:true, search:false, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"modifyuser_xid", label:"修改人id", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"modifyusername", label:"修改人", width:80, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"modifytime", label:"修改时间", width:150, hidden:false, sortable:true, search:false, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"companyid", label:"所属公司", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"ncpRowOperate", label:"操作", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:false, canEdit:false, nullable:true, align:'center'}
  ],
  dispUnitModel:[
    {name:"id", label:"id", editable:true,nullable:false, hidden:true, dispunitType:"text", },
    {name:"code", label:"编码", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"name", label:"名称", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"isactive", label:"已启用", editable:true,nullable:false, hidden:false, dispunitType:"checkbox", },
    {name:"ispublic", label:"是否公共", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", },
    {name:"typename", label:"基础材质", editable:true,nullable:true, hidden:false, dispunitType:"pop", },
    {name:"typeid", label:"基础材质ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"typecode", label:"类型编码", editable:false,nullable:true, hidden:false, dispunitType:"text", },
    {name:"color", label:"颜色", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"imageaccessoryid", label:"贴图附件ID", editable:false,nullable:false, hidden:true, dispunitType:"text", },
    {name:"imagename", label:"贴图", editable:true,nullable:true, hidden:false, dispunitType:"pop", },
    {name:"normalimageaccessoryid", label:"法线贴图ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"normalimagename", label:"法线贴图", editable:true,nullable:true, hidden:false, dispunitType:"pop", },
    {name:"opacity", label:"透明度", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"opacityimageaccessoryid", label:"透明度贴图ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"opacityimagename", label:"透明度贴图", editable:true,nullable:true, hidden:false, dispunitType:"pop", },
    {name:"metalness", label:"金属度", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"metalnessimageaccessoryid", label:"金属度贴图ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"metalnessimagename", label:"金属度贴图", editable:true,nullable:true, hidden:false, dispunitType:"pop", },
    {name:"roughness", label:"粗糙度", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"roughnessimageaccessoryid", label:"粗糙度贴图ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"roughnessimagename", label:"粗糙度贴图", editable:true,nullable:true, hidden:false, dispunitType:"pop", },
    {name:"scalewidth", label:"宽度比例", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"scaleheight", label:"高度比例", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"description", label:"描述", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"createuser_xid", label:"创建人id", editable:false,nullable:true, hidden:true, dispunitType:"text", },
    {name:"createusername", label:"创建人", editable:false,nullable:true, hidden:false, dispunitType:"pop", },
    {name:"createtime", label:"创建时间", editable:false,nullable:true, hidden:false, dispunitType:"time", },
    {name:"modifyuser_xid", label:"修改人id", editable:false,nullable:true, hidden:true, dispunitType:"text", },
    {name:"modifyusername", label:"修改人", editable:false,nullable:true, hidden:false, dispunitType:"pop", },
    {name:"modifytime", label:"修改时间", editable:false,nullable:true, hidden:false, dispunitType:"time", },
    {name:"companyid", label:"所属公司", editable:false,nullable:true, hidden:true, dispunitType:"text", }
  ]
}
