viewModels.p3d_MachineStatus = {
  id:"5ac3e549-762f-4fb6-bc49-d0310a35e81e",
  name:"p3d_MachineStatus",
  dataName:"p3d_MachineStatus",
  title:"物理机状态",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:30, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, align:'center', edittype:"checkbox", dispunitType:"checkbox"},
    {name:"id", label:"id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"name", label:"名称", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createtime", label:"创建时间", width:150, hidden:false, sortable:true, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"modifytime", label:"修改时间", width:150, hidden:false, sortable:true, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"machine_cpu_total", label:"CPU总量(Core)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_cpu_usage", label:"CPU用量(Core)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_cpu_utilisation", label:"CPU使用率", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_disk_read_iops", label:"磁盘每秒读次数(次/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_disk_read_throughput", label:"磁盘每秒读取数据量(Byte/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_disk_size_available", label:"磁盘可用大小(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_disk_size_capacity", label:"磁盘总容量(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_disk_size_usage", label:"磁盘使用量(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_disk_size_utilisation", label:"磁盘使用率", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_disk_write_iops", label:"磁盘每秒写次数(次/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_disk_write_throughput", label:"磁盘每秒写入数据量(Byte/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_memory_available", label:"可用内存(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_memory_total", label:"内存总量(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_memory_usage_wo_cache", label:"内存使用量(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_memory_utilisation", label:"内存使用率", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_net_bytes_received", label:"网络数据接受速率(Byte/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_net_bytes_transmitted", label:"网络数据发送速率(Byte/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"machine_net_utilisation", label:"网络数据传输速率(Byte/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"ncpRowOperate", label:"操作", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:false, canEdit:false, nullable:true, align:'center'}
  ],
  dispUnitModel:[
    {name:"id", label:"id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"name", label:"名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"createtime", label:"创建时间", editable:true,nullable:true, hidden:false, dispunitType:"time", },
    {name:"modifytime", label:"修改时间", editable:true,nullable:true, hidden:false, dispunitType:"time", },
    {name:"machine_cpu_total", label:"CPU总量(Core)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_cpu_usage", label:"CPU用量(Core)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_cpu_utilisation", label:"CPU使用率", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_disk_read_iops", label:"磁盘每秒读次数(次/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_disk_read_throughput", label:"磁盘每秒读取数据量(Byte/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_disk_size_available", label:"磁盘可用大小(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_disk_size_capacity", label:"磁盘总容量(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_disk_size_usage", label:"磁盘使用量(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_disk_size_utilisation", label:"磁盘使用率", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_disk_write_iops", label:"磁盘每秒写次数(次/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_disk_write_throughput", label:"磁盘每秒写入数据量(Byte/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_memory_available", label:"可用内存(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_memory_total", label:"内存总量(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_memory_usage_wo_cache", label:"内存使用量(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_memory_utilisation", label:"内存使用率", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_net_bytes_received", label:"网络数据接受速率(Byte/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_net_bytes_transmitted", label:"网络数据发送速率(Byte/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"machine_net_utilisation", label:"网络数据传输速率(Byte/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", }
  ]
}
