viewModels.p3d_ClusterStatus = {
  id:"7c105653-699d-4d1e-b2fc-b4afd200b950",
  name:"p3d_ClusterStatus",
  dataName:"p3d_ClusterStatus",
  title:"集群状态信息",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:30, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, align:'center', edittype:"checkbox", dispunitType:"checkbox"},
    {name:"id", label:"id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"name", label:"名称", width:150, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"logtime", label:"记录时间", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"statusinfoid", label:"statusinfoid", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"cluster_cpu_total", label:"集群CPU总量(Core)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_cpu_usage", label:"集群CPU用量(Core)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_cpu_utilisation", label:"集群CPU使用率", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_cronjob_count", label:"集群CronJob数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_daemonset_count", label:"集群DaemonSet数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_deployment_count", label:"集群Deployment数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_disk_inode_total", label:"集群inode总数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_disk_inode_usage", label:"集群inode已使用数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_disk_inode_utilisation", label:"集群inode使用率", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_disk_read_iops", label:"集群磁盘每秒读次数(次/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_disk_read_throughput", label:"集群磁盘每秒读取数据量(Byte/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_disk_size_available", label:"集群磁盘可用大小(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_disk_size_capacity", label:"集群磁盘总容量(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_disk_size_usage", label:"集群磁盘使用量(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_disk_size_utilisation", label:"集群磁盘使用率", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_disk_write_iops", label:"集群磁盘每秒写次数(次/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_disk_write_throughput", label:"集群磁盘每秒写入数据量(Byte/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_endpoint_count", label:"集群Endpoint数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_hpa_count", label:"集群HorizontalPodAutoscaler数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_ingresses_extensions_count", label:"集群Ingress数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_job_count", label:"集群Job数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_load1", label:"集群1分钟CPU平均负载", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_load15", label:"集群15分钟CPU平均负载", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_load5", label:"集群5分钟CPU平均负载", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_memory_available", label:"集群可用内存(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_memory_total", label:"集群内存(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_memory_usage_wo_cache", label:"集群内存使用量(Byte)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_memory_utilisation", label:"集群内存使用率", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_namespace_count", label:"集群Namespace数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_net_bytes_received", label:"集群网络数据接受速率(Byte/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_net_bytes_transmitted", label:"集群网络数据发送速率(Byte/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_net_utilisation", label:"集群网络数据传输速率(Byte/s)", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_node_offline", label:"集群节点下线数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_node_offline_ratio", label:"集群节点下线比例", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_node_online", label:"集群节点在线数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_node_total", label:"集群节点总数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_pod_abnormal_count", label:"集群中异常Pod数量", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_pod_abnormal_ratio", label:"集群中异常Pod比例", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_pod_count", label:"集群中调度完成Pod数量", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_pod_quota", label:"集群各节点Pod最大容纳量总和", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_pod_running_count", label:"集群中处于Running阶段5的Pod数量", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_pod_succeeded_count", label:"集群中处于Succeeded阶段的Pod数量", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_pod_utilisation", label:"集群Pod最大容纳量使用率", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_pvc_count", label:"集群PersistentVolumeClaim数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_replicaset_count", label:"集群ReplicaSet数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_secret_count", label:"集群Secret数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_service_count", label:"集群Service数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"cluster_statefulset_count", label:"集群StatefulSet数", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"ncpRowOperate", label:"操作", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:false, canEdit:false, nullable:true, align:'center'}
  ],
  dispUnitModel:[
    {name:"id", label:"id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"name", label:"名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"logtime", label:"记录时间", editable:true,nullable:true, hidden:false, dispunitType:"time", },
    {name:"statusinfoid", label:"statusinfoid", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"cluster_cpu_total", label:"集群CPU总量(Core)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_cpu_usage", label:"集群CPU用量(Core)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_cpu_utilisation", label:"集群CPU使用率", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_cronjob_count", label:"集群CronJob数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_daemonset_count", label:"集群DaemonSet数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_deployment_count", label:"集群Deployment数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_disk_inode_total", label:"集群inode总数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_disk_inode_usage", label:"集群inode已使用数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_disk_inode_utilisation", label:"集群inode使用率", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_disk_read_iops", label:"集群磁盘每秒读次数(次/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_disk_read_throughput", label:"集群磁盘每秒读取数据量(Byte/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_disk_size_available", label:"集群磁盘可用大小(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_disk_size_capacity", label:"集群磁盘总容量(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_disk_size_usage", label:"集群磁盘使用量(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_disk_size_utilisation", label:"集群磁盘使用率", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_disk_write_iops", label:"集群磁盘每秒写次数(次/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_disk_write_throughput", label:"集群磁盘每秒写入数据量(Byte/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_endpoint_count", label:"集群Endpoint数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_hpa_count", label:"集群HorizontalPodAutoscaler数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_ingresses_extensions_count", label:"集群Ingress数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_job_count", label:"集群Job数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_load1", label:"集群1分钟CPU平均负载", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_load15", label:"集群15分钟CPU平均负载", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_load5", label:"集群5分钟CPU平均负载", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_memory_available", label:"集群可用内存(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_memory_total", label:"集群内存(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_memory_usage_wo_cache", label:"集群内存使用量(Byte)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_memory_utilisation", label:"集群内存使用率", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_namespace_count", label:"集群Namespace数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_net_bytes_received", label:"集群网络数据接受速率(Byte/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_net_bytes_transmitted", label:"集群网络数据发送速率(Byte/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_net_utilisation", label:"集群网络数据传输速率(Byte/s)", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_node_offline", label:"集群节点下线数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_node_offline_ratio", label:"集群节点下线比例", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_node_online", label:"集群节点在线数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_node_total", label:"集群节点总数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_pod_abnormal_count", label:"集群中异常Pod数量", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_pod_abnormal_ratio", label:"集群中异常Pod比例", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_pod_count", label:"集群中调度完成Pod数量", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_pod_quota", label:"集群各节点Pod最大容纳量总和", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_pod_running_count", label:"集群中处于Running阶段5的Pod数量", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_pod_succeeded_count", label:"集群中处于Succeeded阶段的Pod数量", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_pod_utilisation", label:"集群Pod最大容纳量使用率", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_pvc_count", label:"集群PersistentVolumeClaim数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_replicaset_count", label:"集群ReplicaSet数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_secret_count", label:"集群Secret数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_service_count", label:"集群Service数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"cluster_statefulset_count", label:"集群StatefulSet数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", }
  ]
}
