viewModels.s3d_ComponentLocalAdmin = {
  id:"40d0cb8a-3e70-425a-be60-d12e7d1b2d77",
  name:"s3d_ComponentLocalAdmin",
  dataName:"s3d_ComponentLocal",
  title:"s3d_ComponentLocal",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:30, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, align:'center', edittype:"checkbox", dispunitType:"checkbox"},
    {name:"id", label:"id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"code", label:"编码", width:120, hidden:false, sortable:false, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"name", label:"名称", width:200, hidden:false, sortable:false, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"versionnum", label:"版本", width:50, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"fileinfodirectory", label:"所属文件夹", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"fileinfotype", label:"文件类型", width:70, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"fileinfoimgname", label:"缩略图名称", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"fileinfofilename", label:"文件名称", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"isactive", label:"已启用", width:50, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'center', canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"ispublic", label:"公共", width:50, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'center', canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"comtypeid", label:"组件类型ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"comtypename", label:"类型名称", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"comtypecode", label:"类型编码", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"scalex", label:"X缩放", width:80, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"scaley", label:"Y缩放", width:80, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"scalez", label:"Z缩放", width:80, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"description", label:"描述", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"ncpRowOperate", label:"操作", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:false, canEdit:false, nullable:true, align:'center'}
  ],
  dispUnitModel:[
    {name:"id", label:"id", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"code", label:"编码", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"name", label:"名称", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"versionnum", label:"版本", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"fileinfodirectory", label:"所属文件夹", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"fileinfotype", label:"文件类型", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"fileinfoimgname", label:"缩略图名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"fileinfofilename", label:"文件名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"isactive", label:"已启用", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", },
    {name:"ispublic", label:"公共", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", },
    {name:"comtypeid", label:"组件类型ID", editable:false,nullable:true, hidden:true, dispunitType:"text", },
    {name:"comtypename", label:"类型名称", editable:true,nullable:true, hidden:false, dispunitType:"pop", },
    {name:"comtypecode", label:"类型编码", editable:false,nullable:true, hidden:false, dispunitType:"text", },
    {name:"scalex", label:"X缩放", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"scaley", label:"Y缩放", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"scalez", label:"Z缩放", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"description", label:"描述", editable:true,nullable:true, hidden:false, dispunitType:"text", }
  ]
}
