viewModels.sys_DataField = {
  id:"4",
  name:"sys_DataField",
  dataName:"sys_DataField",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:30, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, align:'center', edittype:"checkbox", dispunitType:"checkbox"},
    {name:"id", label:"id", width:10, hidden:true, sortable:false, search:false, resizable:false, editable:true, align:'left', canEdit:false, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"parentid", label:"parentid", width:10, hidden:true, sortable:false, search:false, resizable:false, editable:true, align:'left', canEdit:false, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"name", label:"名称", width:120, hidden:false, sortable:true, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"description", label:"描述", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"displayname", label:"提示名", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"valuetype", label:"值类型", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:false, edittype:"text", dispunitType:"list"},
    {name:"issave", label:"可保存", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'center', canEdit:true, nullable:false, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"inputhelptype", label:"输入帮助类型", width:70, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"list"},
    {name:"inputhelpname", label:"输入帮助名称", width:250, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"foreignkeyname", label:"外键字段", width:80, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"valuelength", label:"长度", width:40, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:false, edittype:"text", dispunitType:"decimal"},
    {name:"decimalnum", label:"小数位数", width:40, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'right', canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"isreadonly", label:"只读", width:40, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'center', canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"issum", label:"允许合计", width:80, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'center', canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"notnullable", label:"不可为空", width:80, hidden:false, sortable:false, search:true, resizable:true, editable:true, align:'center', canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"defaultvalue", label:"默认值", width:60, hidden:false, sortable:false, search:true, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"datapurviewfactor", label:"数据权限要素", width:90, hidden:false, sortable:false, search:false, resizable:true, editable:true, align:'left', canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"ncpRowOperate", label:"操作", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:false, canEdit:false, nullable:true, align:'center'}
  ],
  dispUnitModel:[
    {name:"id", label:"id", editable:false,nullable:false, hidden:true, dispunitType:"text", },
    {name:"parentid", label:"parentid", editable:false,nullable:false, hidden:true, dispunitType:"text", },
    {name:"name", label:"名称", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"description", label:"描述", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"displayname", label:"提示名", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"valuetype", label:"值类型", editable:true,nullable:false, hidden:false, dispunitType:"list", },
    {name:"issave", label:"可保存", editable:true,nullable:false, hidden:false, dispunitType:"checkbox", },
    {name:"inputhelptype", label:"输入帮助类型", editable:true,nullable:true, hidden:false, dispunitType:"list", },
    {name:"inputhelpname", label:"输入帮助名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"foreignkeyname", label:"外键字段", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"valuelength", label:"长度", editable:true,nullable:false, hidden:false, dispunitType:"decimal", },
    {name:"decimalnum", label:"小数位数", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"isreadonly", label:"只读", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", },
    {name:"issum", label:"允许合计", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", },
    {name:"notnullable", label:"不可为空", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", },
    {name:"defaultvalue", label:"默认值", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"datapurviewfactor", label:"数据权限要素", editable:true,nullable:true, hidden:false, dispunitType:"text", }
  ]
}
