viewModels.wf_Node = {
  id:"0e1e0cab-3c88-4689-8edd-b8a92874ca03",
  name:"wf_Node",
  dataName:"wf_Node",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:20, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"id", label:"id", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, canEdit:false, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"name", label:"名称", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"nodetype", label:"节点类型", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"triggertype", label:"触发类型", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"positionx", label:"坐标X", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"positiony", label:"坐标Y", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"statusname", label:"状态名称", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"canbackfrom", label:"允许返回", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"canbackto", label:"允许退至", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"groupid", label:"分组", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"actionpageurl", label:"执行页面Url", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"reviewpageurl", label:"查看历史页面地址", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"userdef", label:"审批人", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"userexp", label:"审批人表达式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"backindef", label:"退至执行", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"backinexp", label:"退至执行表达式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"indef", label:"流转至执行", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"inexp", label:"流转至执行表达式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"passdef", label:"通过后执行", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"passexp", label:"通过后执行表达式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"ticketdef", label:"通过票数", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"ticketexp", label:"通过票数表达式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"workflowid", label:"流程id", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, canEdit:false, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"timingexp", label:"定时执行时间表达式", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"description", label:"描述", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"aisid", label:"异步调用服务id", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"aisparameterexp", label:"异步调用参数表达式", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"aisname", label:"异步调用服务名", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"aisparameterconfig", label:"异步调用服务参数设置", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"text"}
  ],
  dispUnitModel:[
    {name:"id", label:"id", editable:false,nullable:false, hidden:true, dispunitType:"text", },
    {name:"name", label:"名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"nodetype", label:"节点类型", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"triggertype", label:"触发类型", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"positionx", label:"坐标X", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"positiony", label:"坐标Y", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"statusname", label:"状态名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"canbackfrom", label:"允许返回", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", },
    {name:"canbackto", label:"允许退至", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", },
    {name:"groupid", label:"分组", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"actionpageurl", label:"执行页面Url", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"reviewpageurl", label:"查看历史页面地址", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"userdef", label:"审批人", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"userexp", label:"审批人表达式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"backindef", label:"退至执行", editable:true,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"backinexp", label:"退至执行表达式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"indef", label:"流转至执行", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"inexp", label:"流转至执行表达式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"passdef", label:"通过后执行", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"passexp", label:"通过后执行表达式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"ticketdef", label:"通过票数", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"ticketexp", label:"通过票数表达式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"workflowid", label:"流程id", editable:false,nullable:false, hidden:true, dispunitType:"text", },
    {name:"timingexp", label:"定时执行时间表达式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"description", label:"描述", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"aisid", label:"异步调用服务id", editable:false,nullable:true, hidden:true, dispunitType:"text", },
    {name:"aisparameterexp", label:"异步调用参数表达式", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"aisname", label:"异步调用服务名", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"aisparameterconfig", label:"异步调用服务参数设置", editable:false,nullable:true, hidden:false, dispunitType:"text", }
  ]
}
